ALTER TABLE usuario
ALTER COLUMN email DROP NOT NULL;

ALTER TABLE usuario
ALTER COLUMN description DROP NOT NULL;

ALTER TABLE usuario
ALTER COLUMN birthdate DROP NOT NULL;

ALTER TABLE usuario
ALTER COLUMN pictureurl DROP NOT NULL;